filter:
    paths: [src/*, tests/*]

default_config:
    checkstyle: ~
    verify_php_doc_comments: ~
    doc_comment_fixes: ~

path_configs:
    tests:
        paths: [tests/*]
        checkstyle: false
        verify_php_doc_comments: false
        doc_comment_fixes: false
